name: test

on:
  push:
    paths:
      - ".github/workflows/test.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: sleep 5

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
