name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yaml"
      - "upper/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: pwd && ls -al
      - uses: actions/checkout@v4
      - run: pwd && ls -al
      - uses: actions/setup-go@v5
        with:
          # go-version: '1.22'
          go-version-file: ./upper/go.mod
          cache-dependency-path: ./upper/go.sum
      - run: go version
      - run: |
          ls
          cd upper
          go build
          ls
          go test
